name: QEMU instance
author: Jakub Pieńkowski
description: Launch a QEMU instance with user networking as a systemd service
inputs:
  name:
    description: Hostname and systemd service name
    default: ci-instance
  extra_size:
    description: How much to enlarge disk, e.g. 10G
    default: 10G
  memory:
    description: Memory expressed in megabytes
    default: 1024
  cpu:
    description: Virtual CPUs quantity
    default: 1
  image_url:
    description: URL to QCOW2 image
    default: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2
  dir:
    description: Directory where instance data will be placed
    default: ci-instance
  ssh_port:
    description: Port number on local machine to forward to remote SSH
    default: 8022
  ssh_user:
    description: User for SSH and sudo access
    default: ci-instance
  shell:
    description: Path to shell for SSH user
    default: /bin/bash
  kvm:
    description: Set to 1 in order to use KVM acceleration
    default: 0
runs:
  using: composite
  steps:
    - name: Start QEMU instance
      run: ${{ github.action_path }}/main.sh
      shell: bash
      env:
        QEMU_INSTANCE_EXTRA_SIZE: ${{ inputs.extra_size }}
        QEMU_INSTANCE_MEMORY: ${{ inputs.memory }}
        QEMU_INSTANCE_CPU: ${{ inputs.cpu }}
        QEMU_INSTANCE_IMAGE_URL: ${{ inputs.image_url }}
        QEMU_INSTANCE_DIR: ${{ inputs.dir }}
        QEMU_INSTANCE_SSH_PORT: ${{ inputs.ssh_port }}
        QEMU_INSTANCE_SSH_USER: ${{ inputs.ssh_user }}
        QEMU_INSTANCE_NAME: ${{ inputs.name }}
        QEMU_INSTANCE_SHELL: ${{ inputs.shell }}
        QEMU_INSTANCE_KVM: ${{ inputs.kvm }}
