name: test
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
jobs:
  test:
    strategy:
      matrix:
        image_url:
          # Apine Linux 3.19.1
          - https://dl-cdn.alpinelinux.org/alpine/v3.19/releases/cloud/nocloud_alpine-3.19.1-x86_64-bios-cloudinit-r0.qcow2
          # Debian 12
          - https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2
          # Debian 11
          - https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-amd64.qcow2
          # Rocky Linux 9
          - http://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base.latest.x86_64.qcow2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          key: ${{ matrix.image_url }}
          path: |
            ci-instance/image.qcow2

      - name: Launch instance
        uses: ./
        with:
          image_url: ${{ matrix.image_url }}

      - name: Test SSH connection
        run: ssh -F ci-instance/ssh_config ci-instance echo Hello
